<?php
/**
 ************************************************************************
 * Copyright [2017] [RakutenPay]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************
 */

?>
<script type="text/javascript">
  (function(window, document){

    if(!!window["RPay"]) return;

    var head = document.getElementsByTagName("head")[0];
    var script = document.createElement("script");
    script.async = 1;
<?php if(strtolower(Mage::getStoreConfig('payment/connector/environment')) == "sandbox"): ?>
    script.src = "https://static.rakutenpay.com.br/rpayjs/rpay-latest.dev.min.js";
<?php else: ?>
    script.src = "https://static.rakutenpay.com.br/rpayjs/rpay-latest.min.js";
<?php endif ?>
    head.appendChild(script);

  })(window, document)
</script>

<script type="text/javascript">
//<![CDATA[
var x = document.getElementsByTagName("script");
  var header_already_added = false;
  for (var i=0; i< x.length; i++){
      if (x[i].src == "<?php echo $this->getSkinUrl('rakuten/connector/rakutenpay/js/rakutenpay-before-save.js') ?>"){
             header_already_added = true;
      }
  }

  if (header_already_added == false){
    // add header if not already added
    var head = document.getElementsByTagName("head")[0];
    var s = document.createElement('script');
    s.type = 'text/javascript';
    s.src = '<?php echo $this->getSkinUrl('rakuten/connector/rakutenpay/js/rakutenpay-before-save.js') ?>';
    head.appendChild(s);
  }
//]]>
</script>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div id="rakutenpay-billet-method-div"></div>
    <input type="hidden" id="boletoHash" value="" name="payment[boleto_hash]">
    <div style="float: left">
        <div class="rakutenpay-boleto-label-div">
            <label class="rakutenpay-required" ><?php echo $this->__('CPF ou CNPJ') ?></label>
        </div>
        <div class="rakutenpay-cc-input-div">
            <input
                class="rakutenpay-cc-input"
                id="bilitDocument"
                onblur="validateDocument(this)"
                onkeydown="documentMask(event, this)"
                type="text"
                title="<?php echo $this->__('CPF ou CNPJ') ?>"
                name="payment[boleto_cpf]"
                value=""
                maxlength="18"
                data-rkp="card-holder-document"
            />
            <div class="display-none validation-advice bilitDocument-error-message">Insira um CPF ou CNPJ válido</div>
        </div>

    <ul style="float: left;" class="rakutenpay-direct-payment-ul">
        <li>&#9679; Imprima o boleto e pague no banco ou na internet utilizando o seu c&oacute;digo de barras</li>
    <?php if(\Mage::getStoreConfig('payment/connector_rakutenpay_boleto/expiration') == 1): ?>
        <li>&#9679; O prazo de validade do boleto &eacute; de 1 dia.</li>
    <?php else: ?>
        <li>&#9679; O prazo de validade do boleto &eacute; de
            <?= \Mage::getStoreConfig('payment/connector_rakutenpay_boleto/expiration') ?> dias.</li>
    <?php endif ?>
    </ul>

  </div>
<!--    <div style="display: inline-block; "class="rakutenpay-label-spacing rakutenpay-cc-group-div">
        <ul class="rakutenpay-direct-payment-ul">
            <div class="rakutenpay-cc-input-div">
                <li>Esta compra está sendo feita no Brasil
                    <img class="flag-origin-country-img" src="<?php echo $this->getSkinUrl('rakuten/connector/rakutenpay/images/flag-origin-country.png'); ?>">
                </li>
            </div>
        </ul>
    </div>-->
</div>
