<?php
/**
 ************************************************************************
 * Copyright [2018] [RakutenConnector]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************
 */

?>
<div class="page-head">
    <h2 class="sub-title">Finalizando sua compra com RakutenPay</h2>
</div>
<script type="text/javascript">
    window.onload = function () {
        window.open('<?= Mage::registry('link') ?>', '_blank');
    };
</script>
<table style="width:100%;">
    <tr>
        <td style="width:100%">
            Sua compra está em processo de finalização, aguarde um instante.<br>
            Se a página de pagamento não abrir automaticamente
            <a href="<?= Mage::registry('link') ?>" target="_blank">clique aqui</a>.
        </td>
    </tr>
</table>
