<?php
/**
 ************************************************************************
 * Copyright [2017] [RakutenPay]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************
 */

?>
<script>
    <?php if (array_key_exists('billet', $_GET)): ?>
    <?php
    $http = new \RakutenConnector\Resources\RakutenPay\Http();
    $http->get($_GET['billet'], 20, 'ISO-8859-1', false);
    $response = \RakutenConnector\Resources\Responsibility::http($http,
            new \RakutenConnector\Parsers\DirectPayment\Boleto\Billet());
    ?>
    function pop_up() {
        var win = window.open('', '_blank');
        win.document.body.innerHTML = `<?= $response ?>`;
    }
    <?php endif ?>
</script>

    <?php if (array_key_exists('billet', $_GET)) { ?>
        <div class="buttons-set">
            <input type="button" class="button" onclick="pop_up();" value="Clique aqui para imprimir seu Boleto" />
        </div>
    <?php } ?>
