<?php
/**
 ************************************************************************
 * Copyright [2018] [RakutenConnector]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************
 */

?>
<?php $billet = (array_key_exists('billet', $_GET)) ? $_GET['billet'] : false; ?>
<script>
    var startLoading = function() {
        document.getElementById("open-billet").disabled = true;
    };

    var stopLoading = function() {
        document.getElementById("open-billet").disabled = false;
    };

    function popUp() {
        startLoading();

        var http = new XMLHttpRequest();
        var url = "<?php echo $this->getUrl('rakutenpay/billet/getBillet'); ?>";
        var params = "data=<?php echo $billet; ?>";
        http.open('POST', url, true);

        http.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');

        http.onreadystatechange = function() {
            if (http.readyState == 4 && http.status == 200) {
                stopLoading();
                var w = window.open();
                w.document.body.innerHTML = http.responseText;
            }
        }
        http.send(params);
    }
</script>

    <?php if (array_key_exists('billet', $_GET)) { ?>
        <div class="buttons-set">
            <input type="button" id="open-billet" class="button" onclick="popUp();" value="Clique aqui para imprimir seu Boleto" />
        </div>
    <?php } ?>
