<?php
/**
 ************************************************************************
 * Copyright [2018] [RakutenConnector]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************
 */

?>
<?php $billet = (array_key_exists('billet', $_GET)) ? $_GET['billet'] : false; ?>
<script>

    var startLoading = function() {
        jQuery('#open-billet').attr('disabled','disabled');
    };

    var stopLoading = function() {
        jQuery('#open-billet').removeAttr('disabled');
    };

    function pop_up() {
        startLoading();
        jQuery.ajax({
            url: "<?php echo $this->getUrl('rakutenpay/billet/getBillet'); ?>",
            type: "POST",
            data: {
                data: "<?php echo $billet; ?>"
            },
            success: function (data) {
                stopLoading();
                var w = window.open();
                jQuery(w.document.body).html(data);
            }
        });
    }
</script>

    <?php if (array_key_exists('billet', $_GET)) { ?>
        <div class="buttons-set">
            <input type="button" id="open-billet" class="button" onclick="pop_up();" value="Clique aqui para imprimir seu Boleto" />
        </div>
    <?php } ?>
