<?php
/**
 ************************************************************************
 * Copyright [2017] [RakutenPay]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************
 */
$helper = Mage::helper('rakutenpay');

$productPrice = Mage::registry('current_product')->getFinalPrice();
$installments = $helper->installmentsModel()->create($productPrice);

if ($installments) {
    $countInstallment = count($installments);
    $halfInstallment = ceil($countInstallment/2);

    $totalAmount = str_replace('.', ',', $installments[$countInstallment-1]['totalAmount']);

    echo "<table class=\"rakutenpay-installments-table\"><caption>Ou pague em até {$installments[$countInstallment-1]['text']} (Total a prazo R\${$totalAmount})</caption><tbody>";

    for($i = 0; $i < $halfInstallment; $i++) {
        echo "<tr><td>{$installments[$i]['text']}</td>";
        if (isset($installments[$i + $halfInstallment]['text'])) {
            echo "<td>{$installments[$i + $halfInstallment]['text']}</td>";
        }
        echo "</tr>";
    }
    echo "</tbody></table>";
}
