<?php
/**
 ************************************************************************
 * Copyright [2018] [RakutenConnector]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************
 */
?>
<script>
    var startLoading = function() {
        document.getElementById("open-billet-feedback").innerHTML = '<span style="font-weight: bold">(aguarde o carregamento...)</span>';
    };

    var stopLoading = function() {
        document.getElementById("open-billet-feedback").innerHTML = '(<a href="#" onclick="popUp();">clique aqui</a> para visualizar)';
    };

    function popUp() {
        startLoading();

        var http = new XMLHttpRequest();
        var url = "<?php echo $this->getUrl('rakutenpay/billet/getBillet'); ?>";
        var params = "data=<?php echo $this->getBilletUrl(); ?>";
        http.open('POST', url, true);

        http.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');

        http.onreadystatechange = function() {
            if (http.readyState == 4 && http.status == 200) {
                stopLoading();
                var w = window.open();
                w.document.body.innerHTML = http.responseText;
            }
        }
        http.send(params);
    }
</script>

<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
<?php if(!empty($this->getBilletUrl())): ?>
    <span id="open-billet-feedback">(<a href="#" onclick="popUp();">clique aqui</a> para visualizar)</span>
<?php endif;?>
