<?php
/**
 ************************************************************************
 * Copyright [2018] [RakutenConnector]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************
 */
?>
<script>

    var startLoading = function() {
        jQuery('#open-billet-feedback').replaceWith('<span id="open-billet-feedback" style="font-weight: bold">(aguarde o carregamento...)</span>')
    };

    var stopLoading = function() {
        jQuery('#open-billet-feedback').replaceWith('<span id="open-billet-feedback">(<a href="#" data-behavior="open-billet" onclick="pop_up();">clique aqui</a> para visualizar)</span>')
    };

    function pop_up() {
        startLoading();
        jQuery.ajax({
            url: "<?php echo $this->getUrl('rakutenpay/billet/getBillet'); ?>",
            type: "POST",
            data: {
                data: "<?php echo $this->getBilletUrl(); ?>"
            },
            success: function (data) {
                stopLoading();
                var w = window.open();
                jQuery(w.document.body).html(data);
            }
        });
    }
</script>

<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
<?php if(!empty($this->getBilletUrl())): ?>
    <span id="open-billet-feedback">(<a href="#" data-behavior="open-billet" onclick="pop_up();">clique aqui</a> para visualizar)</span>
<?php endif;?>
